
source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle zsh-users/zsh-completions
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle z
antigen bundle arzzen/calc.plugin.zsh
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle peterhurford/git-it-on.zsh
alias m=make
alias cm=cmake
alias v=vim
# Load the theme.
antigen theme agnoster
#POWERLEVEL9K_MODE='nerdfont-complete'
# done.
antigen apply
