### VTE Setup (nonlogin shell problem)
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  # on Ubuntu it's in vte-2.91.sh sometimes for whatever reason?
  if [[ -s '/etc/profile.d/vte.sh' ]]; then
    Z_VTE_CONF_SETUP_FILE='/etc/profile.d/vte.sh'
  elif [[ -s '/etc/profile.d/vte-2.91.sh' ]]; then
    Z_VTE_CONF_SETUP_FILE='/etc/profile.d/vte-2.91.sh'
  fi

  if [[ -n "$Z_VTE_CONF_SETUP_FILE" ]]; then
    source $Z_VTE_CONF_SETUP_FILE
  fi
fi

source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle zsh-users/zsh-completions
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle z
# antigen bundle arzzen/calc.plugin.zsh
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle peterhurford/git-it-on.zsh
antigen bundle colored-man-pages
alias m=make
alias cm=cmake
alias v=vim
alias py=python
alias a=atom
alias n=nautilus
alias hugo='ssh aiden@blu.blu.utk.edu'
# Load the theme.
antigen bundle https://gitlab.com/robobenklein/p10k
#POWERLEVEL9K_MODE='nerdfont-complete'
# done.
#
antigen apply

if [[ ${precmd_functions[(r)_z_precmd]} == "_z_precmd" ]]; then
  # move the _z_precmd to the prexec, so it only adds with commands executed,
  # not with prompts drawn
  precmd_functions=(${precmd_functions%_z_precmd})
  preexec_functions+=(_z_precmd)
fi

# cprp fancy cp
if (( ${+commands[rsync]} )); then
  function cprp () {
    rsync -r --info=progress2 --delay-updates --partial-dir=.rsync-partial "$@"
  }
  compdef _rsync cprp
fi
