# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### VTE Setup (nonlogin shell problem)
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  # on Ubuntu it's in vte-2.91.sh sometimes for whatever reason?
  if [[ -s '/etc/profile.d/vte.sh' ]]; then
    Z_VTE_CONF_SETUP_FILE='/etc/profile.d/vte.sh'
  elif [[ -s '/etc/profile.d/vte-2.91.sh' ]]; then
    Z_VTE_CONF_SETUP_FILE='/etc/profile.d/vte-2.91.sh'
  fi

  if [[ -n "$Z_VTE_CONF_SETUP_FILE" ]]; then
    source $Z_VTE_CONF_SETUP_FILE
  fi
fi

source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle zsh-users/zsh-completions
# antigen bundle zsh-users/zsh-autosuggestions
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle z
# antigen bundle arzzen/calc.plugin.zsh
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle peterhurford/git-it-on.zsh
antigen bundle colored-man-pages
alias m=make
alias cm=cmake
alias v=vim
alias py=python
alias a=atom
alias n=nautilus
#TODO: Context specific aliases
alias hugo='ssh aiden@blu.blu.utk.edu'
alias hydra='ssh arutter1@hydra24.eecs.utk.edu'
alias venv='python3 -m venv'
# Load the theme.
# antigen bundle robobenklein/zinc
#POWERLEVEL9K_MODE='nerdfont-complete'
# done.
#
# antigen apply
# External plugins
# source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# zinc_opts=(
#   zincs_cwd ';;;;rtab;-t;-l'
# )
# prompt_zinc_setup

# if [[ ${precmd_functions[(r)_z_precmd]} == "_z_precmd" ]]; then
#   # move the _z_precmd to the prexec, so it only adds with commands executed,
#   # not with prompts drawn
#   precmd_functions=(${precmd_functions%_z_precmd})
#   preexec_functions+=(_z_precmd)
# fi

# cprp fancy cp
if (( ${+commands[rsync]} )); then
  function cprp () {
    rsync -r --info=progress2 --delay-updates --partial-dir=.rsync-partial "$@"
  }
  compdef _rsync cprp
fi
# export PATH="/home/solsane/miniconda3/bin:$PATH"
export PATH="/bin:/usr/bin:/usr/local/bin:$PATH"
# export PATH="/usr/bin/python3/bin:$PATH"
# autoload -U up-line-or-beginning-search
# autoload -U down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/solsane/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/solsane/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/solsane/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/solsane/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
# app switching only does current workspace
# gsettings set org.gnome.shell.app-switcher current-workspace-only true

# Docker installation
# https://docs.docker.com/engine/install/ubuntu/

# if on ubuntu, install gnome shell extensions

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
antigen theme romkatv/powerlevel10k
antigen apply
